name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: master
          owner: ytdl-org 
          merge_method: rebase 
          auto_approve: true
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
